site_name: Carpo Docs
theme:
  name: 'mkdocs'
  language: en
  highlightjs: true
  nav_style: dark
  hljs_languages:
    - java
    -
repo_name: '6point6/carpo'
repo_url: 'https://github.com/6point6/carpo'

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Concepts:
      - Properties: concepts/properties.md
  - Modules:
      - Common: modules/common.md
      - Case: modules/case_data.md
  - Contributing: contributing.md