name: Release

on:
  release:
    types: [published]


jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        module:
          - carpo-parent
          - carpo-common
          - carpo-case-data
          - carpo-mi
          - carpo-mi-spring-boot
          - carpo-serialization

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh                        # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_NEXUS_USER       # env variable for username in deploy
          server-password: MAVEN_NEXUS_PASSWORD   # env variable for token in deploy

      - name: Copy GPG Private key
        run: echo "${{ secrets.gpg_private_key }}" > private-key.txt && gpg --import --no-tty --batch --yes private-key.txt
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Set version
        run: mvn versions:set -DnewVersion=${{ steps.previoustag.outputs.tag }} -f carpo-parent/pom.xml
      - name: Build
        run: mvn -B clean install --file pom.xml
      - name: Deploy to Maven Central respository
        env:
          MAVEN_NEXUS_USER: ${{ secrets.nexus_username }}
          MAVEN_NEXUS_PASSWORD: ${{ secrets.nexus_password }}
        run: |
          cd ${{ matrix.module }}
          mvn deploy -Dgpg.passphrase=${{ secrets.gpg_passphrase }} -DskipTests -P deploy
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.module }}
          path: ${{ matrix.module }}/target

  upversion:

    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@master"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@master"
        with:
          title: ${{ steps.semvers.outputs.minor }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
